exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex('stonks').del()
    .then(function () {
      // Inserts seed entries
      return knex('stonks').insert([
        {
          id: 1,
          esg_id: 11119,
          company_name: 'Algonquin Power & Utilities Corp.',
          exchange_symbol: 'TSE',
          stock_symbol: 'AQN',
          environment_grade: 'AA',
          environment_level: 'Excellent',
          social_grade: 'BB',
          social_level: 'Medium',
          governance_grade: 'BB',
          governance_level: 'Medium',
          total_grade: 'A',
          total_level: 'High',
          last_processing_date: '04-11-2021',
          environment_score: 671,
          social_score: 341,
          governance_score: 300,
          total: 1312
        },
        {
          id: 2,
          esg_id: 2664,
          company_name: 'Facebook, Inc.',
          exchange_symbol: 'NASDAQ',
          stock_symbol: 'FB',
          environment_grade: 'A',
          environment_level: 'High',
          social_grade: 'B',
          social_level: 'Medium',
          governance_grade: 'BB',
          governance_level: 'Medium',
          total_grade: 'BBB',
          total_level: 'High',
          last_processing_date: '30-11-2021',
          environment_score: 505,
          social_score: 273,
          governance_score: 315,
          total: 1093
        },
        {
          id: 3,
          esg_id: 348,
          company_name: 'AMC Entertainment Holdings, Inc.',
          exchange_symbol: 'NYSE',
          stock_symbol: 'AMC',
          environment_grade: 'B',
          environment_level: 'Medium',
          social_grade: 'B',
          social_level: 'Medium',
          governance_grade: 'B',
          governance_level: 'Medium',
          total_grade: 'B',
          total_level: 'Medium',
          last_processing_date: '14-11-2021',
          environment_score: 210,
          social_score: 216,
          governance_score: 200,
          total: 626
        },
        {
          id: 4,
          esg_id: 2994,
          company_name: 'GameStop Corp.',
          exchange_symbol: 'NYSE',
          stock_symbol: 'GME',
          environment_grade: 'BB',
          environment_level: 'Medium',
          social_grade: 'B',
          social_level: 'Medium',
          governance_grade: 'BB',
          governance_level: 'Medium',
          total_grade: 'BB',
          total_level: 'Medium',
          last_processing_date: '30-11-2021',
          environment_score: 335,
          social_score: 226,
          governance_score: 300,
          total: 861
        },
        {
          id: 5,
          esg_id: 7009,
          company_name: 'Tesla, Inc.',
          exchange_symbol: 'NASDAQ',
          stock_symbol: 'TSLA',
          environment_grade: 'A',
          environment_level: 'High',
          social_grade: 'CC',
          social_level: 'Low',
          governance_grade: 'CCC',
          governance_level: 'Low',
          total_grade: 'BB',
          total_level: 'Medium',
          last_processing_date: '03-11-2021',
          environment_score: 580,
          social_score: 146,
          governance_score: 155,
          total: 881
        },
        {
          id: 6,
          esg_id: 5604,
          company_name: 'Pfizer Inc.',
          exchange_symbol: 'NYSE',
          stock_symbol: 'PFE',
          environment_grade: 'A',
          environment_level: 'High',
          social_grade: 'BB',
          social_level: 'Medium',
          governance_grade: 'BB',
          governance_level: 'Medium',
          total_grade: 'BBB',
          total_level: 'High',
          last_processing_date: '01-12-2021',
          environment_score: 510,
          social_score: 300,
          governance_score: 305,
          total: 1115
        },
        {
          id: 7,
          esg_id: 502,
          company_name: 'Apple Inc.',
          exchange_symbol: 'NASDAQ',
          stock_symbol: 'AAPL',
          environment_grade: 'BB',
          environment_level: 'Medium',
          social_grade: 'B',
          social_level: 'Medium',
          governance_grade: 'B',
          governance_level: 'Medium',
          total_grade: 'BB',
          total_level: 'Medium',
          last_processing_date: '14-11-2021',
          environment_score: 360,
          social_score: 275,
          governance_score: 260,
          total: 895
        },
        {
          id: 8,
          esg_id: 342,
          company_name: 'Amazon.com, Inc.',
          exchange_symbol: 'NASDAQ',
          stock_symbol: 'AMZN',
          environment_grade: 'AA',
          environment_level: 'Excellent',
          social_grade: 'BBB',
          social_level: 'High',
          governance_grade: 'BB',
          governance_level: 'Medium',
          total_grade: 'A',
          total_level: 'High',
          last_processing_date: '14-11-2021',
          environment_score: 690,
          social_score: 402,
          governance_score: 315,
          total: 1407
        },
        {
          id: 9,
          esg_id: 4720,
          company_name: 'Microsoft Corporation',
          exchange_symbol: 'NASDAQ',
          stock_symbol: 'MSFT',
          environment_grade: 'BBB',
          environment_level: 'High',
          social_grade: 'B',
          social_level: 'Medium',
          governance_grade: 'B',
          governance_level: 'Medium',
          total_grade: 'BB',
          total_level: 'Medium',
          last_processing_date: '01-12-2021',
          environment_score: 455,
          social_score: 238,
          governance_score: 225,
          total: 918
        },
        {
          id: 10,
          esg_id: 5244,
          company_name: 'NVIDIA Corporation',
          exchange_symbol: 'NASDAQ',
          stock_symbol: 'NVDA',
          environment_grade: 'BB',
          environment_level: 'Medium',
          social_grade: 'BB',
          social_level: 'Medium',
          governance_grade: 'B',
          governance_level: 'Medium',
          total_grade: 'BB',
          total_level: 'Medium',
          last_processing_date: '01-12-2021',
          environment_score: 343,
          social_score: 303,
          governance_score: 275,
          total: 921
        },
        {
          id: 11,
          esg_id: 132,
          company_name: 'Advanced Micro Devices, Inc.',
          exchange_symbol: 'NASDAQ',
          stock_symbol: 'AMD',
          environment_grade: 'B',
          environment_level: 'Medium',
          social_grade: 'B',
          social_level: 'Medium',
          governance_grade: 'B',
          governance_level: 'Medium',
          total_grade: 'B',
          total_level: 'Medium',
          last_processing_date: '14-11-2021',
          environment_score: 205,
          social_score: 214,
          governance_score: 200,
          total: 619
        },
        {
          id: 12,
          esg_id: 9828,
          company_name: 'Fox Marble Holdings PLC',
          exchange_symbol: 'LON',
          stock_symbol: 'FOX',
          environment_grade: 'DDD',
          environment_level: 'Low',
          social_grade: 'B',
          social_level: 'Medium',
          governance_grade: 'B',
          governance_level: 'Medium',
          total_grade: 'B',
          total_level: 'Medium',
          last_processing_date: '04-12-2021',
          environment_score: 65,
          social_score: 273,
          governance_score: 290,
          total: 628
        },
        {
          id: 13,
          esg_id: 7644,
          company_name: 'The Walt Disney Company',
          exchange_symbol: 'NYSE',
          stock_symbol: 'DIS',
          environment_grade: 'A',
          environment_level: 'High',
          social_grade: 'BB',
          social_level: 'Medium',
          governance_grade: 'BB',
          governance_level: 'Medium',
          total_grade: 'BBB',
          total_level: 'High',
          last_processing_date: '02-12-2021',
          environment_score: 500,
          social_score: 316,
          governance_score: 310,
          total: 1126
        },
        {
          id: 14,
          esg_id: 7391,
          company_name: 'Universal Corporation',
          exchange_symbol: 'NYSE',
          stock_symbol: 'UVV',
          environment_grade: 'A',
          environment_level: 'High',
          social_grade: 'BB',
          social_level: 'Medium',
          governance_grade: 'BB',
          governance_level: 'Medium',
          total_grade: 'BBB',
          total_level: 'High',
          last_processing_date: '02-12-2021',
          environment_score: 500,
          social_score: 372,
          governance_score: 300,
          total: 1172
        },
        {
          id: 15,
          esg_id: 4368,
          company_name: 'Lockheed Martin Corporation',
          exchange_symbol: 'NYSE',
          stock_symbol: 'LMT',
          environment_grade: 'A',
          environment_level: 'High',
          social_grade: 'BB',
          social_level: 'Medium',
          governance_grade: 'BB',
          governance_level: 'Medium',
          total_grade: 'BBB',
          total_level: 'High',
          last_processing_date: '01-12-2021',
          environment_score: 500,
          social_score: 306,
          governance_score: 310,
          total: 1116
        },
        {
          id: 16,
          esg_id: 326,
          company_name: 'Altria Group, Inc.',
          exchange_symbol: 'NYSE',
          stock_symbol: 'MO',
          environment_grade: 'A',
          environment_level: 'High',
          social_grade: 'BB',
          social_level: 'Medium',
          governance_grade: 'BB',
          governance_level: 'Medium',
          total_grade: 'BBB',
          total_level: 'High',
          last_processing_date: '14-11-2021',
          environment_score: 545,
          social_score: 302,
          governance_score: 340,
          total: 1187
        },
        {
          id: 17,
          esg_id: 11221,
          company_name: 'HEXO Corp.',
          exchange_symbol: 'TSE',
          stock_symbol: 'HEXO',
          environment_grade: 'A',
          environment_level: 'High',
          social_grade: 'BB',
          social_level: 'Medium',
          governance_grade: 'BB',
          governance_level: 'Medium',
          total_grade: 'BBB',
          total_level: 'High',
          last_processing_date: '04-12-2021',
          environment_score: 518,
          social_score: 312,
          governance_score: 310,
          total: 1140
        },
        {
          id: 18,
          esg_id: 24634,
          company_name: 'Bangkok Airways Public Company Limited',
          exchange_symbol: 'BKK',
          stock_symbol: 'BA',
          environment_grade: 'B',
          environment_level: 'Medium',
          social_grade: 'B',
          social_level: 'Medium',
          governance_grade: 'B',
          governance_level: 'Medium',
          total_grade: 'B',
          total_level: 'Medium',
          last_processing_date: '06-11-2021',
          environment_score: 210,
          social_score: 205,
          governance_score: 220,
          total: 635
        },
        {
          id: 19,
          esg_id: 72102,
          company_name: 'NIO Inc.',
          exchange_symbol: 'NYSE',
          stock_symbol: 'NIO',
          environment_grade: 'BB',
          environment_level: 'Medium',
          social_grade: 'B',
          social_level: 'Medium',
          governance_grade: 'B',
          governance_level: 'Medium',
          total_grade: 'BB',
          total_level: 'Medium',
          last_processing_date: '13-11-2021',
          environment_score: 377,
          social_score: 298,
          governance_score: 210,
          total: 885
        },
        {
          id: 20,
          esg_id: 2494,
          company_name: 'Enphase Energy, Inc.',
          exchange_symbol: 'NASDAQ',
          stock_symbol: 'ENPH',
          environment_grade: 'AA',
          environment_level: 'Excellent',
          social_grade: 'BB',
          social_level: 'Medium',
          governance_grade: 'BB',
          governance_level: 'Medium',
          total_grade: 'A',
          total_level: 'High',
          last_processing_date: '30-11-2021',
          environment_score: 740,
          social_score: 383,
          governance_score: 315,
          total: 1438
        },
        {
          id: 21,
          esg_id: 7732,
          company_name: 'Weyerhaeuser Company',
          exchange_symbol: 'NYSE',
          stock_symbol: 'WY',
          environment_grade: 'AA',
          environment_level: 'Excellent',
          social_grade: 'BB',
          social_level: 'Medium',
          governance_grade: 'BB',
          governance_level: 'Medium',
          total_grade: 'A',
          total_level: 'High',
          last_processing_date: '02-12-2021',
          environment_score: 643,
          social_score: 325,
          governance_score: 300,
          total: 1268
        },
        {
          id: 22,
          esg_id: 3799,
          company_name: 'Intel Corporation',
          exchange_symbol: '',
          stock_symbol: 'INTC',
          environment_grade: 'BB',
          environment_level: 'Medium',
          social_grade: 'BB',
          social_level: 'Medium',
          governance_grade: 'BBB',
          governance_level: 'High',
          total_grade: 'BBB',
          total_level: 'High',
          last_processing_date: '30-11-2021',
          environment_score: 350,
          social_score: 325,
          governance_score: 465,
          total: 1140
        },
        {
          id: 23,
          esg_id: 6407,
          company_name: 'Shell Midstream Partners, L.P.',
          exchange_symbol: 'NYSE',
          stock_symbol: 'SHLX',
          environment_grade: 'DDD',
          environment_level: 'Low',
          social_grade: 'B',
          social_level: 'Medium',
          governance_grade: 'BB',
          governance_level: 'Medium',
          total_grade: 'B',
          total_level: 'Medium',
          last_processing_date: '02-12-2021',
          environment_score: 70,
          social_score: 258,
          governance_score: 318,
          total: 646
        },
        {
          id: 24,
          esg_id: 6807,
          company_name: 'Sunrun Inc.',
          exchange_symbol: 'NASDAQ',
          stock_symbol: 'RUN',
          environment_grade: 'AA',
          environment_level: 'Excellent',
          social_grade: 'BB',
          social_level: 'Medium',
          governance_grade: 'B',
          governance_level: 'Medium',
          total_grade: 'A',
          total_level: 'High',
          last_processing_date: '02-12-2021',
          environment_score: 740,
          social_score: 360,
          governance_score: 230,
          total: 1330
        }
      ])
    })
}
