exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex('stonks').del()
    .then(function () {
      // Inserts seed entries
      return knex('stonks').insert([
        {
          id: 1,
          esg_id: 11119,
          company_name: 'Algonquin Power & Utilities Corp.',
          exchange_symbol: 'TSE',
          stock_symbol: 'AQN',
          environment_grade: 'AA',
          environment_level: 'Excellent',
          social_grade: 'BB',
          social_level: 'Medium',
          governance_grade: 'BB',
          governance_level: 'Medium',
          total_grade: 'A',
          total_level: 'High',
          last_processing_date: '04-11-2021',
          environment_score: 671,
          social_score: 341,
          governance_score: 300,
          total: 1312
        },
        {
          id: 2,
          esg_id: 2664,
          company_name: 'Facebook, Inc.',
          exchange_symbol: 'NASDAQ',
          stock_symbol: 'FB',
          environment_grade: 'A',
          environment_level: 'High',
          social_grade: 'B',
          social_level: 'Medium',
          governance_grade: 'BB',
          governance_level: 'Medium',
          total_grade: 'BBB',
          total_level: 'High',
          last_processing_date: '30-11-2021',
          environment_score: 505,
          social_score: 273,
          governance_score: 315,
          total: 1093
        },
        {
          id: 3,
          esg_id: 348,
          company_name: 'AMC Entertainment Holdings, Inc.',
          exchange_symbol: 'NYSE',
          stock_symbol: 'AMC',
          environment_grade: 'B',
          environment_level: 'Medium',
          social_grade: 'B',
          social_level: 'Medium',
          governance_grade: 'B',
          governance_level: 'Medium',
          total_grade: 'B',
          total_level: 'Medium',
          last_processing_date: '14-11-2021',
          environment_score: 210,
          social_score: 216,
          governance_score: 200,
          total: 626
        },
        {
          id: 4,
          esg_id: 2994,
          company_name: 'GameStop Corp.',
          exchange_symbol: 'NYSE',
          stock_symbol: 'GME',
          environment_grade: 'BB',
          environment_level: 'Medium',
          social_grade: 'B',
          social_level: 'Medium',
          governance_grade: 'BB',
          governance_level: 'Medium',
          total_grade: 'BB',
          total_level: 'Medium',
          last_processing_date: '30-11-2021',
          environment_score: 335,
          social_score: 226,
          governance_score: 300,
          total: 861
        },
        {
          id: 5,
          esg_id: 7009,
          company_name: 'Tesla, Inc.',
          exchange_symbol: 'NASDAQ',
          stock_symbol: 'TSLA',
          environment_grade: 'A',
          environment_level: 'High',
          social_grade: 'CC',
          social_level: 'Low',
          governance_grade: 'CCC',
          governance_level: 'Low',
          total_grade: 'BB',
          total_level: 'Medium',
          last_processing_date: '03-11-2021',
          environment_score: 580,
          social_score: 146,
          governance_score: 155,
          total: 881
        },
        {
          id: 6,
          esg_id: 5604,
          company_name: 'Pfizer Inc.',
          exchange_symbol: 'NYSE',
          stock_symbol: 'PFE',
          environment_grade: 'A',
          environment_level: 'High',
          social_grade: 'BB',
          social_level: 'Medium',
          governance_grade: 'BB',
          governance_level: 'Medium',
          total_grade: 'BBB',
          total_level: 'High',
          last_processing_date: '01-12-2021',
          environment_score: 510,
          social_score: 300,
          governance_score: 305,
          total: 1115
        }
      ])
    })
}
