name: Node.js CI

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install modules
        run: npm i
      - name: Run linting
        run: npm run lint
      - name: Run unit tests
        run: npm run test
